server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 19961024
    url: jdbc:mysql://localhost:3306/whctest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
#  mapper-locations: classpath:mybatis-config.xml
  type-aliases-package: com.whc.data.eneity


